spring:
  application:
    name: messaging-writer-service
  
  profiles:
    active: local
  
  data:
    mongodb:
      host: localhost
      port: 27017
      database: turknet-messaging-db
      username: admin
      password: password
      authentication-database: admin
  
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: messaging-writer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  kafka:
    topics:
      message-commands: turknet.transformers.message.commands.0
      message-commands-retry: turknet.transformers.message.commands.retry.0
      user-commands: turknet.transformers.user.commands.0
      user-commands-retry: turknet.transformers.user.commands.retry.0
      session-commands: turknet.transformers.session.commands.0
      session-commands-retry: turknet.transformers.session.commands.retry.0
    retry:
      max-retry: 5
      cron: "*/10 * * * *"

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.github.melihemreguler.messagingwriterservice: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN

---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      host: mongodb
      port: 27017
      database: turknet-messaging-db
      username: admin
      password: password
      authentication-database: admin
  
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: messaging-writer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  kafka:
    topics:
      message-commands: turknet.transformers.message.commands.0
      message-commands-retry: turknet.transformers.message.commands.retry.0
      user-commands: turknet.transformers.user.commands.0
      user-commands-retry: turknet.transformers.user.commands.retry.0
      session-commands: turknet.transformers.session.commands.0
      session-commands-retry: turknet.transformers.session.commands.retry.0
    retry:
      max-retry: 5
      cron: "*/10 * * * *"
