server:
  port: 8080
  error:
    include-stacktrace: never
    include-exception: false
    include-message: never
    include-binding-errors: never

spring:
  application:
    name: turknet-messaging-service
  profiles:
    active: local

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/turknet-messaging-db?authSource=admin
      database: turknet-messaging-db

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: turknet-messaging-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
app:
  kafka:
    topics:
      # Command topics - for sending commands to consumer services
      user-commands: ${USER_COMMANDS_TOPIC:turknet.transformers.user.commands.0}
      user-commands-retry: ${USER_COMMANDS_RETRY_TOPIC:turknet.transformers.user.commands.retry.0}
      message-commands: ${MESSAGE_COMMANDS_TOPIC:turknet.transformers.message.commands.0}
      message-commands-retry: ${MESSAGE_COMMANDS_RETRY_TOPIC:turknet.transformers.message.commands.retry.0}
      session-commands: ${SESSION_COMMANDS_TOPIC:turknet.transformers.session.commands.0}
      session-commands-retry: ${SESSION_COMMANDS_RETRY_TOPIC:turknet.transformers.session.commands.retry.0}
  session:
    expiration-hours: ${SESSION_EXPIRATION_HOURS:24}
    cleanup-interval-minutes: ${SESSION_CLEANUP_INTERVAL_MINUTES:60}

logging:
  level:
    root: INFO
    com.github.melihemreguler.turknetmessagingservice: DEBUG

springdoc:
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

# Actuator configuration for health checks
management:
  server:
    port: 8080  # Same port as main application
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,readiness,liveness
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    readiness:
      enabled: true
    liveness:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

---
# Docker profile configuration
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/turknet-messaging-db?authSource=admin
  kafka:
    bootstrap-servers: kafka:9092

app:
  kafka:
    topics:
      # Command topics - for sending commands to consumer services
      user-commands: ${USER_COMMANDS_TOPIC:turknet.transformers.user.commands.0}
      user-commands-retry: ${USER_COMMANDS_RETRY_TOPIC:turknet.transformers.user.commands.retry.0}
      message-commands: ${MESSAGE_COMMANDS_TOPIC:turknet.transformers.message.commands.0}
      message-commands-retry: ${MESSAGE_COMMANDS_RETRY_TOPIC:turknet.transformers.message.commands.retry.0}
      session-commands: ${SESSION_COMMANDS_TOPIC:turknet.transformers.session.commands.0}
      session-commands-retry: ${SESSION_COMMANDS_RETRY_TOPIC:turknet.transformers.session.commands.retry.0}

  session:
    expiration-hours: ${SESSION_EXPIRATION_HOURS:24}
    cleanup-interval-minutes: ${SESSION_CLEANUP_INTERVAL_MINUTES:60}

logging:
  level:
    root: INFO
    com.github.melihemreguler.turknetmessagingservice: INFO  # Production'da DEBUG yerine INFO

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}  # Production'da varsayılan olarak kapalı
    path: /api/swagger-ui.html
  api-docs:
    enabled: ${SWAGGER_ENABLED:false}
    path: /v3/api-docs

# Actuator configuration for health checks
management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,readiness,liveness  # Production'da sınırlı exposure
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:when-authorized}  # Production'da güvenli
      show-components: ${HEALTH_SHOW_COMPONENTS:when-authorized}
      probes:
        enabled: true
    readiness:
      enabled: true
    liveness:
      enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
